project:
  type: website
  output-dir: blog
website:
  title: "Rice&Beans"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/chagas98
      - text: "{{< iconify fa6-brands square-x-twitter >}}"
        href: https://twitter.com/schagas98
format:
  html:
    theme: [journal, custom.scss]
    css: styles.css



